### ISSUE TITLE
[ISSUE] show desktop button

### ISSUE THREAD

**Issue by Tarazet** [martinet101/ElevenClock#336]
There was a feature request i was also looking forward to.
The feature aparently got implemented with version 2.6 and i am looking to enable it in 2.8.0

Here the original Request #233 for reference:
https://github.com/martinet101/ElevenClock/issues/233

**Comment by martinet101** [comment]
Yes, you have to enable show desktop button under taskbar settings. (I'm sorry its not in english, but it should do the trick)

![image](https://user-images.githubusercontent.com/53119851/144263605-adfc1803-e689-4bac-b52e-a0def3200e94.png)


It shows like this when hovering the mouse over it:
![image](https://user-images.githubusercontent.com/53119851/144263657-8899e411-81cc-4b2f-954e-1f961a238170.png)

**Comment by Tarazet** [comment]
it is enabled and shows on my main monitor. Does this work for 2nd Monitor where i use ElevenClock?

**Comment by martinet101** [comment]
Yep, i'll take a look

**Comment by martinet101** [comment]
Fixed, on next release there will be a better desktop button

**Comment by Tarazet** [comment]
thanks, it is better now and i like it a lot.

But it still doesn't reach the very corner of the screen:
![grafik](https://user-images.githubusercontent.com/70140279/145680991-fe567fa5-f354-41b3-bdae-d8358a3f5982.png)

like the button is not a rectangle but an elipse. It does cover completely to the right and completely to the bottom just not the corner (if i put my mouse without watching where it is all the way to the corner it just misses the button by a few pixels).

**Comment by martinet101** [comment]
Oh, i see, didn't realize. Gonna fix it

**Comment by martinet101** [comment]
There might be some kind of border or sth

**Comment by Tarazet** [comment]
fast reply. Thanks a lot 👍 
as mentioned it does work completely on the border right and below

**Comment by martinet101** [comment]
Fixed. This will come with next week's update.
