### ISSUE TITLE
ElevenClock: how to display hours and minutes

### ISSUE THREAD

**Issue by MurraySobol** [martinet101/ElevenClock#480]
I have just installed ElevenClock on my Windows 11 64-bit laptop.
I wish to add hours and minutes, but not seconds, to the date displayed.
Is it possible to do this thru this program?
Thanks

**Comment by MurraySobol** [comment]
resolved.

**Comment by Sonic1305** [comment]
Not sure if it is related to this but I cannot remove the seconds out of my time. I even tried removing the seconds from the windows regional settings and they still appear. For record I am using my pc in german, so maybe it is related to the translation?

**Comment by martinet101** [comment]
Try this:

Q: The clock shows seconds when the "Show Seconds" settings is disabled
A: Check that you don't have seconds set in your regional settings and disable seconds following this article's instructions
