### ISSUE TITLE
[ISSUE] Windows Defender Trojan Detection

### ISSUE THREAD

**Issue by Andrew-Koman** [martinet101/ElevenClock#503]
I saw there was another issue of Avast finding ElevenClock, but I did not see one for Windows Defender.
Below is a screenshot of the scan

![image](https://user-images.githubusercontent.com/35636935/149834660-699ba38a-8af1-4adb-ae37-60ffb576f8c6.png)

**Comment by Ataye** [comment]
Yea, i just got the same.

**Comment by lepinwalrus16** [comment]
Also detected as trojan by my windows defender

**Comment by FinnKrestel** [comment]
Same here under KB2267602

**Comment by CalemRoelofs** [comment]
+1 same here

**Comment by Vlken** [comment]
+1

**Comment by Masamune3210** [comment]
Guys, if its detected by one person running defender its gonna be detected by all on latest definitions, don't need 5 people saying that they all got detected lol

**Comment by CalemRoelofs** [comment]
https://www.virustotal.com/gui/file/f6f0e06ca0ce4db2d3d57de9cff616d55db53de59db55b417bb10a92ff0f5d69 
Flagged by 10 different vendors so far in VirusTotal (3.1.0 binary)

**Comment by fussel132** [comment]
Whoops. Was there an update of elevenclock in the background or does Defender updated something right now? Just saw a threat popping up as my second clock popped away xD

**Comment by Masamune3210** [comment]
Im guessing either its gotten popular enough for the heuristic engine to have finally picked it up, or some malicious actor submitted it as malicious

**Comment by CalemRoelofs** [comment]
Looks like this has already been addressed in issue https://github.com/martinet101/ElevenClock/issues/489

**Comment by fussel132** [comment]
How unfortunate. The problem still seems to be PyInstaller as I guess

**Comment by FinnKrestel** [comment]
I'm currently trying to compile ElevenClock in a sandbox and see the results.

**Comment by rush2sk8** [comment]
Same here Win11 Windows Defender showing it as a trojan

**Comment by FinnKrestel** [comment]
Getting similar results from a freshly compiled binary: https://www.virustotal.com/gui/file/4cde25ac416bce725176f4347f6b5b30e98e2769b97b87532d4d717d7e9d3030

**Comment by Andrew-Koman** [comment]
> Looks like this has already been addressed in issue #489

I saw that issue, I just assumed because the exe was submitted as an exception to Avast that it would not fix any other scans for it.

**Comment by fussel132** [comment]
As a temporary fix, you can whitelist ElevenClock.exe in Defender > Virus and Threat Protection > Manage Settings and then at the very bottom you can add C:\Users\user\AppData\Local\Programs\ElevenClock\ElevenClock.exe to be excluded from Windows Defender.

**Comment by bitpushr** [comment]
Also flagged in BitDefender.

**Comment by Lajull-fr** [comment]
> As a temporary fix, you can whitelist ElevenClock.exe in Defender > Virus and Threat Protection > Manage Settings and then at the very bottom you can add C:\Users\user\AppData\Local\Programs\ElevenClock\ElevenClock.exe to be excluded from Windows Defender.

No thanks 😉

**Comment by play0** [comment]
> Guys, if its detected by one person running defender its gonna be detected by all on latest definitions, don't need 5 people saying that they all got detected lol

You need a few to say it's not isolated. 

+1 

:P

**Comment by play0** [comment]
I'm going to submit the .exe in question [Here](https://www.microsoft.com/en-us/wdsi/filesubmission/) so MS can white list it.

**Comment by martinet101** [comment]
Ok guys, i'll rebiuld the .exe ASAP with another builder, to see if that fixees  the issue

**Comment by martinet101** [comment]
Updates have been paused. install version 3.0 and i'll fix this asap.

**Comment by martinet101** [comment]
See status:  https://twitter.com/ElevenClockProj/status/1483351974259142657

**Comment by martinet101** [comment]
Check version 3.1.1

**Comment by martinet101** [comment]
It is not flagged anymore
