### ISSUE TITLE
[BUG] (Crashing minutes after lauch)

### ISSUE THREAD

**Issue by BartokW** [martinet101/ElevenClock#596]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>
 

</b>

## Describe the bug
Crashing shortly after launch, will only stay running for a few minutes at most.

## To Reproduce
Steps to reproduce the behaviour:
1. Start ElevenClock
2. Wait a few minutes

## Expected behaviour
Expected to continue running

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.1 (v3.21) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 2560, 1440)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(2360, 1392, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy-MM-dd
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%Y-%m-%d
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 Restart loop: 1
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-2560, 0, 2560, 1440)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 1392, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy-MM-dd
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%Y-%m-%d
🔵 Full screen rect:  (-2560, 0, 0, 1440)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🟠 Monitor blacklisted!
🔵 Initializing clock 3...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-2563, -768, 1360, 768)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-1403, -48, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy-MM-dd
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%Y-%m-%d
🔵 Full screen rect:  (-2563, -768, -1203, 0)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🟢 Loaded clocks in 0.9559996128082275
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟢 Cached text input host hwnd: 66646
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🟣 Expected AttributeError on backgroundLoop thread
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.6369996070861816
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/error.webp
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Saving log...

```

**Comment by kslifter** [comment]
I started having the same issue after it updated today.

**Comment by martinet101** [comment]
Please guys post on #590

**Comment by BartokW** [comment]
I don't see any issue with fonts in the error log, it's just crashing.

**Comment by martinet101** [comment]
Im sorry then, didn't understand you.

Have you tried resetting elevenclock?

**Comment by kevinf100** [comment]
Same thing is happening, but I'm not sure if it is that log.
`---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.1 (v3.21) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟠 Monitor blacklisted!
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(1920, 143, 1600, 900)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3320, 995, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (1920, 143, 3520, 1043)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 2...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1600, 120, 1600, 900)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 972, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (-1600, 120, 0, 1020)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 0.34278440475463867
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 0.8680992126464844
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/error.webp
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/error.webp
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Saving log...
🟢 log saved successfully
`
Doesn't seem to crash from this, it crashes from something else minutes later.
Reinstalling caused an insta crash on first run.
Also not the updater, disable it and error still shows.

**Comment by BartokW** [comment]
I have tried doing a reset and it's still crashing.

**Comment by martinet101** [comment]
Yes, i've actually realised that mine is crashing too.

**Comment by kslifter** [comment]
Mine has not crashed so far today! I did notice though that my icons in the right hand corner are gone though...probably not related.

**Comment by kslifter** [comment]
I ended up just needing to slide my clock horizontally to the left till the arrow appeared.

**Comment by kevinf100** [comment]
> Yes, i've actually realised that mine is crashing too.

Is the debug .bat file suppose to be ran with something else? The program seems to silently crash even with the debug batch file.

**Comment by martinet101** [comment]
Yes, even the python script is crashing with python 3.9.10

I've been testing it with 3.9.9 and so far so good...

**Comment by martinet101** [comment]
I guess i'll downgrade

**Comment by martinet101** [comment]
I have good news! The cuplrit was a corrupt python installation. I've made a new clean environment, and an urgent update will be released asap fixing the issue!

**Comment by martinet101** [comment]
Update to the latest version, it should now work

**Comment by BartokW** [comment]
Even with 3.2.2 it still seems to be crashing shortly after launch, and I'm not getting any log messages showing.

**Comment by martinet101** [comment]
Weird, for me it started working again.

Have you tried uninstalling, deleting the .elevenclock folder and installing again?

**Comment by BartokW** [comment]
I have now, and it's still crashing. Seems to run for a little longer than it was before, but there's also nothing in the log.  Is there a file location with log information I could grab for you?

**Comment by BartokW** [comment]
Looking at Event Viewer I found this.

> Faulting application name: ElevenClock.exe, version: 1.9.7.30920, time stamp: 0x5fb4e109
Faulting module name: Qt5Core.dll, version: 5.15.2.0, time stamp: 0x5fa4dd3b
Exception code: 0xc0000005
Fault offset: 0x00000000001d69db
Faulting process id: 0x54ac
Faulting application start time: 0x01d822ac74e59664
Faulting application path: C:\Users\jonw_\AppData\Local\Programs\ElevenClock\ElevenClock.exe
Faulting module path: C:\Users\jonw_\AppData\Local\Temp\_MEI293322\Qt5Core.dll
Report Id: 5a300473-ff85-4762-a97f-1b70593e1a66
Faulting package full name: 
Faulting package-relative application ID:

**Comment by martinet101** [comment]
The log being empty is my fault, but the crash idk what happened. Sometimes, dll files fail to load because of system corruption. Can you please follow this guide?https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

**Comment by BartokW** [comment]
I've done that and no issues were found.  It's weird, it runs perfectly for a couple minutes, and then just disappears. Added the same error to the Event Viewer, I've even tried cleaning out the temp folder to make sure there's no collisions when launching again.

**Comment by brumasribera** [comment]
I'm having the same problem here. It crashes right after opening the Setting app.

**Comment by martinet101** [comment]
If Version 3.1.1 worked please disable updates and downgrade

**Comment by BartokW** [comment]
It would crash with previous versions as well, just not as frequently (several hours) but I hadn't gotten around to looking for logs / error messages.  I'll give it a try.

**Comment by kevinf100** [comment]
Seems to be the same crash, Slient, with debug build logs showing nothing.

**Comment by martinet101** [comment]
> It would crash with previous versions as well, just not as frequently (several hours) but I hadn't gotten around to looking for logs / error messages.  I'll give it a try.

Then that's a different issue, because there was a crash that was fixed with this latest version due to python corruption.

**Comment by martinet101** [comment]
Could you please open a new one?

**Comment by kevinf100** [comment]
> > It would crash with previous versions as well, just not as frequently (several hours) but I hadn't gotten around to looking for logs / error messages.  I'll give it a try.
> 
> Then that's a different issue, because there was a crash that was fixed with this latest version due to python corruption.

This crash is still happening. Same thing is happening, Eleven Just seems to die with nothing in logs or debug build. Eventviewer shows what' they are having to.

**Comment by sinusinu** [comment]
I am having crashes since 3.2.1 too :(
`git bisect` shows that the first bad commit is 0d60779, and Qt documentation says that [Qt is not thread-safe unless specified](https://doc.qt.io/qt-5/threads-reentrancy.html).
So...maybe that can be the root of this problem?

**Comment by BartokW** [comment]
I'm getting the same crash on 3.2.0 as well. Haven't checked any older versions yet to see when it might have been introduced.

**Comment by martinet101** [comment]
> 

There you go. Didn't realise that. Thank you @sinusinu :). That is 100% the culprit

**Comment by martinet101** [comment]
Gonna fix it and publish a new release

**Comment by brumasribera** [comment]
Great Martí! Moltes gràcies!

**Comment by martinet101** [comment]
Ara quan pugui publicaré una actualització.

I'm going to publish an update ASAP

**Comment by martinet101** [comment]
The update is live now!

**Comment by brumasribera** [comment]
Funciona com un tiro. Gràcies Martí! Una realment útil 😊🙏

It works as a charm!
