### ISSUE TITLE
[BUG/ISSUE] Python line 1450 issue / crash after a few seconds

### ISSUE THREAD

**Issue by rexor2405** [martinet101/ElevenClock#727]
## Describe the bug
Following crash report: 

                        OS: Windows
                   Version: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: 3.4.0
          APP Version Code: 3.4
                   Program: ElevenClock

-----------------------------------------------------------------------------------------

ElevenClock Log:

Traceback (most recent call last):
  File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1450, in <module>
  File ".\settings.py", line 172, in __init__

ValueError: '' is not in list<class 'ValueError'>: '' is not in list

## To Reproduce
Steps to reproduce the behaviour:
1. Try to open Eleven Clock
4. After a few seconds eleven clock crashes.

## The Log

```
I can't paste the log since eleven clock crashes after a few seconds
```

**Comment by martinet101** [comment]
Please reinstall, the issue has been fixed

**Comment by ArnoudBM** [comment]
This is still happening on my machine, running the latest at the time of writing
Sent in an error report.
OS: Windows
                   Version: ('10', '10.0.22598', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: 3.4.0
          APP Version Code: 3.4
                   Program: ElevenClock

**Comment by martinet101** [comment]
Try to install the microsoft store version, since you are now installing version 3.4.0 and not 3.4.0.1, the fixed one.
