### ISSUE TITLE
Regional clocks show local time

### ISSUE THREAD

**Issue by Rayman256** [martinet101/ElevenClock#737]
## Before submitting the issue

- [ Y] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ Y] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ Y] **I have checked that I am running the latest version of ElevenClock**
- [ Y] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ Y] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
The regional clocks shown on hovering show the same time as the local time.

## To Reproduce
Steps to reproduce the behaviour:
1. Add additional regional clocks
2. Hover over ElevenClock time
3. See error

## Expected behaviour
The clocks should show the time in the regions specified.

## Screenshots
![image](https://user-images.githubusercontent.com/101151641/161455419-08e2dd90-ff20-4d85-8407-853edde6d600.png)

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 
Win32mica: Failed to DwmExtendFrameIntoClientArea -2147024809
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.4.0.1 (v3.401) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2360, 1393, 200, 46)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 Restart loop: 1
🔵 Initializing clock 1...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(2560, 0, 2560, 1440)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(4920, 1393, 200, 46)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#d/%m/%Y
🔵 Full screen rect:  (2560, 0, 5120, 1440)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
🟡 Desktop button enabled
🟢 Loaded clocks in 1.505678653717041
🟢 Cached text input host hwnd: 66554
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute 1
🟣 Expected AttributeError on backgroundLoop thread
Win32mica: Failed to SetWindowCompositionAttribute 1
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.1690120697021484
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 512, in wrap_socket

🔴   File "ssl.py", line 1070, in _create

🔴   File "ssl.py", line 1341, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 127, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
Win32mica: Failed to SetWindowCompositionAttribute 1
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/customize.webp
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 512, in wrap_socket

🔴   File "ssl.py", line 1070, in _create

🔴   File "ssl.py", line 1341, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 127, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: h:mm tt
🔵 Long date string: h:mm tt
🔵 Long date string: dddd, d MMMM yyyy
Win32mica: Failed to SetWindowCompositionAttribute 1
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...


If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

## Additional context
At one point, an additional tooltip opened up that showed the correct information, but I've been unable to replicate that
This will be a helpful new feature, once working - Thanks

**Comment by tylertylerday** [comment]
I'm also having the same issue.

**Comment by martinet101** [comment]
I guys, could you please export you current settings and attach the file here?
thanks :)

**Comment by ChrisRomp** [comment]
This?

```
Win32mica: Failed to DwmExtendFrameIntoClientArea -2147024809
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.4.0.1 (v3.401) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(-319, -1440, 3440, 1440)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2921, -46, 200, 44)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M:%S 
%A
%#m/%#d/%Y
🔵 Full screen rect:  (-319, -1440, 3121, 0)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 1.4962024688720703
🔵 Restart loop: 1
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
🟣 Expected AttributeError on backgroundLoop thread
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.224979877471924
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: HH:mm
🔵 Long date string: HH:mm
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Showing tooltip
🔵 Long date string: HH:mm
🔵 Long date string: HH:mm
🔵 Long date string: dddd, MMMM d, yyyy
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/customize.webp
🔵 Showing tooltip
🔵 Long date string: HH:mm
🔵 Long date string: HH:mm
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Showing tooltip
🔵 Long date string: HH:mm
🔵 Long date string: HH:mm
🔵 Long date string: dddd, MMMM d, yyyy
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
🔵 Copying log to the clipboard...
```

**Comment by ChrisRomp** [comment]
I only see export log, not a way to export the settings. Hope the log is sufficient but let me know if the settings export is somewhere else.

**Comment by Rayman256** [comment]
Here you go

Hi Chris
See below for the place to do this
***@***.***

Thanks and Regards
Richard

Phone: +61 (0) 2 9489 0059
Mobile: +61 (0) 409 151 147

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/162529026-d3016183-fd79-4ed4-aadb-399402927a3c.png)

**Comment by martinet101** [comment]
You can export from there

**Comment by ChrisRomp** [comment]
```
DefaultPrefsLoaded|@||~|DisableHideOnFullScreen|@||~|EnableSeconds|@||~|EnableSilentUpdates|@||~|EnableWeekDay|@||~|FullScreenPrefsWereMigrated|@||~|NewFullScreenMethod|@||~|Updated2.8Already|@||~|
```

**Comment by Rayman256** [comment]
[ElevenClock Settings 220409.txt](https://github.com/martinet101/ElevenClock/files/8457255/ElevenClock.Settings.220409.txt)

Now as a txt file.
Sorry, it was originally saved as a .esf

**Comment by martinet101** [comment]
> Sorry, it was originally saved as a .esf

It was meant to, no worries :)

**Comment by martinet101** [comment]
Hi, The issue has been fixed, it was due to some incompatibilites with the datetime library and PyInstaller.

**Comment by Rayman256** [comment]
Hi Marti
Just checking that the fix is in the next version – correct?
I reinstalled the current version and still have the issue


Thanks and Regards
Richard

Phone: +61 (0) 2 9489 0059
Mobile: +61 (0) 409 151 147

**Comment by martinet101** [comment]
Yes, the _next_ version has not been released yet, i've been busy
