### ISSUE TITLE
Wrong zh_TW font

### ISSUE THREAD

**Issue by xsm1997** [martinet101/ElevenClock#916]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
I cannot change the fonts of tooltip and the right click menu of tray icon using Simplified Chinese (China) as language. The font is always a serif font (not sure which font exactly it is, seems like 仿宋 (FangSong)), and it is considered ugly by some people like me. In addition, the default font of Windows 11 in Chinese environments is a sans-serif font called 微软雅黑UI (Microsoft YaHei UI, or msyh UI), which is visually like the font of settings window. All windows apps use Microsoft YaHei UI by default, including the Settings window. I think it is better to use the default Windows font and fix the bug that users cannot change the font.

## Screenshots
<img width="134" alt="image" src="https://user-images.githubusercontent.com/4453837/189501079-75de6287-7413-4f24-a6a0-a67edac01499.png">

![image](https://user-images.githubusercontent.com/4453837/189501101-456bb561-aff4-4a03-abbb-67ac61a9451b.png)

![image](https://user-images.githubusercontent.com/4453837/189501109-46d54d0b-eb7d-4507-a2bc-d6952507ffa6.png)

## The Log

```
It took 0.0009989738464355469 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.8.1 (v3.81) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "zh_CN"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1394, 200, 46)
🔵 Font families   : ['Microsoft YaHei UI', 'Segoe UI Variable', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/M/d
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S 
%Y/%#m/%#d
🔵 Full screen rect:  (0, 0, 2560, 1440)
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:True
🟡 Desktop button enabled
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(-1480, 1394, 200, 46)
🔵 Font families   : ['Microsoft YaHei UI', 'Segoe UI Variable', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/M/d
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S 
%Y/%#m/%#d
🔵 Full screen rect:  (-3840, 0, -1280, 1440)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:True
can't parse ""
🟡 Desktop button enabled
🟢 Loaded clocks in 0.29454517364501953
{'System language': 'default', 'Arabic - عربي\u200e (66%)': 'ar', 'Bulgarian - български (19%)': 'bg', 'Catalan - Català': 'ca', 'Czech - Čeština': 'cs', 'Danish - Dansk (25%)': 'da', 'German - Deutsch (98%)': 'de', 'Greek - Ελληνικά (20%)': 'el', 'English - English': 'en', 'Spanish - Español (98%)': 'es', 'Estonian - eesti (98%)': 'et', 'Persian - فارسی\u200e (5%)': 'fa', 'Finnish - Suomi (67%)': 'fi', 'French - Français (98%)': 'fr', 'Hebrew - עִבְרִית\u200e (98%)': 'he', 'Hungarian - Magyar (98%)': 'hu', 'Indonesian - Bahasa Indonesia (98%)': 'id', 'Italian - Italiano (51%)': 'it', 'Japanese - 日本語 (98%)': 'ja', 'Korean - 한국어': 'ko', 'Lithuanian - Lietuvių (24%)': 'lt', 'Latvian - Latviski (65%)': 'lv', 'Norwegian (bokmål) (98%)': 'nb', 'Dutch - Nederlands (86%)': 'nl', 'Norwegian (nynorsk) (72%)': 'nn', 'Polish - Polski (98%)': 'pl', 'Portuguese (Brazil) (84%)': 'pt_BR', 'Portuguese (Portugal) (98%)': 'pt_PT', 'Romanian - Română (98%)': 'ro', 'Russian - Русский (98%)': 'ru', 'Sinhala - සිංහල': 'si', 'Slovak - Slovenčina (32%)': 'sk', 'Serbian - Srpski (24%)': 'sr', 'Swedish - Svenska (79%)': 'sv', 'Thai - ภาษาไทย (85%)': 'th', 'Turkish - Türkçe (21%)': 'tr', 'Ukranian - Yкраї́нська (26%)': 'ua', 'Vietnamese - Tiếng Việt (41%)': 'vi', 'Simplified Chinese (China) (98%)': 'zh_CN', 'Traditional Chinese (Taiwan) (98%)': 'zh_TW'}
🔵 Restart loop: 1
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.4539415836334229
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: https://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://upload.wikimedia.org/wikipedia/commons/d/db/Google_Translate_Icon.png
🔵 Copying log to the clipboard...

```

**Comment by xsm1997** [comment]
By the way there is no issue with the font on the clock.

**Comment by xsm1997** [comment]
Traditional Chinese (Taiwan) is also affected by this bug.

**Comment by martinet101** [comment]
Does Traditional chinese also use Microsoft YaHei UI?

**Comment by xsm1997** [comment]
> Does Traditional chinese also use Microsoft YaHei UI?

No, Traditional Chinese use the serif font, the same as Simplified Chinese.

**Comment by martinet101** [comment]
FangSong?

**Comment by xsm1997** [comment]
> FangSong?

Yes, it seems like it, but I am not sure.

**Comment by xsm1997** [comment]
> FangSong?

Maybe it is SongTi, which is the default font of Windows XP, 2003, etc.

**Comment by xsm1997** [comment]
> FangSong?

It looks like SongTi (SimSun) rendered in TrueType for now. Because Windows XP render SimSun in dots, I did not recognize it in the first look.

**Comment by martinet101** [comment]
Ok, Thanks!

**Comment by martinet101** [comment]
Fixed!

**Comment by xsm1997** [comment]
Please use Microsoft Jhenghei UI for zh_TW, not SimSun.

By the way, the font of right-click context menu is not fixed (still SimSun).

**Comment by martinet101** [comment]
Done!
